### ISSUE TITLE
extract_feature: numpy.core._exceptions._UFuncNoLoopError

### ISSUE THREAD

**Issue by nick-youngblut** [ZhaoXM-Lab/metaMIC#1]
I'm running the following on my dataset:

```
metaMIC extract_feature --mlen 5000 -t 8 -m meta   --pileup pileup.txt --bam metaspades.bam           --contig contigs_filtered.fasta --output test
```

```
2021-07-12 14:21:28,537 - Start metaMIC
2021-07-12 14:21:29,957 - Step: Feature extraction
Process Process-4:
Traceback (most recent call last):
  File "/ebio/abt3_projects/test/.snakemake/conda/efef0c0639418737003b248bfdc4e478/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/ebio/abt3_projects/test/.snakemake/conda/efef0c0639418737003b248bfdc4e478/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/ebio/abt3_projects/test/.snakemake/conda/efef0c0639418737003b248bfdc4e478/lib/python3.9/site-packages/metaMIC/extract.py", line 437, in read_breakpoint_cal
    window_read_breakpoint_data = window_break_cal(read_breakpoint_data)
  File "/ebio/abt3_projects/test/.snakemake/conda/efef0c0639418737003b248bfdc4e478/lib/python3.9/site-packages/metaMIC/extract.py", line 389, in window_break_cal
    data['index'] = data['contig'] + '_' + \
  File "/ebio/abt3_projects/test/.snakemake/conda/efef0c0639418737003b248bfdc4e478/lib/python3.9/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/ebio/abt3_projects/test/.snakemake/conda/efef0c0639418737003b248bfdc4e478/lib/python3.9/site-packages/pandas/core/arraylike.py", line 92, in __add__
    return self._arith_method(other, operator.add)
  File "/ebio/abt3_projects/test/.snakemake/conda/efef0c0639418737003b248bfdc4e478/lib/python3.9/site-packages/pandas/core/series.py", line 5525, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/ebio/abt3_projects/test/.snakemake/conda/efef0c0639418737003b248bfdc4e478/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 224, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "/ebio/abt3_projects/test/.snakemake/conda/efef0c0639418737003b248bfdc4e478/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 166, in _na_arithmetic_op
    result = func(left, right)
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('float64'), dtype('<U1')) -> None
```

```
    data['index'] = data['contig'] + '_' + \
        [str(int(x)) for x in data['start_pos']]
```

It appears that `[str(int(x)) for x in data['start_pos']]` did not have the correct object type for the string concatenation, seemingly due to a `None` value.

**Comment by nick-youngblut** [comment]
`[str(int(x)) for x in data['start_pos']]` returns an empty list (`[]`), which is causing the error. 

More generally, `data['index'] = data['contig'] + '_' + [str(int(x)) for x in data['start_pos']]` should always generate an error, given that string cannot be concatenated with a list

**Comment by nick-youngblut** [comment]
I traced this issue back to the `read_breakpoint_per_contig()` function. For all reads in my dataset, `read.is_supplementary` is `False` and `read.get_cigar_stats()[0][4]` is `0`, so `data` is an empty DataFrame, which eventually causes the downstream error.

Why do you assume that some reads are supplementary and/or have certain cigar string flags?

**Comment by ZhaoXM-Lab** [comment]
Actually, only few reads is supplementary, so read.is_supplementary is False and read.get_cigar_stats()[0][4] is normal. We are still working on some not good-designed code.

**Comment by nick-youngblut** [comment]
The issue is that ALL reads meet those criteria, so the `data` DataFrame is empty, which causes errors downstream. 

The code is generally pretty good (IMHO); there's just a few things that could be edited to avoid issues

**Comment by ZhaoXM-Lab** [comment]
> I traced this issue back to the `read_breakpoint_per_contig()` function. For all reads in my dataset, `read.is_supplementary` is `False` and `read.get_cigar_stats()[0][4]` is `0`, so `data` is an empty DataFrame, which eventually causes the downstream error.
> 
> Why do you assume that some reads are supplementary and/or have certain cigar string flags?

So you mean that the file "temp/read_breakpoint_per_base.txt" you got is empty?

**Comment by nick-youngblut** [comment]
The DataFrame that holds all reads marked as supplementary is empty. The metaMIC code iterates through the reads and loads a DataFrame with just reads with the designation:

```
read.is_supplementary == False and read.get_cigar_stats()[0][4] == 0
```

If no reads match these criteria, then the DataFrame remains empty, and the empty DataFrame causes downstream errors.

**Comment by GeoMicroSoares** [comment]
FYI @ZhaoXM-Lab  I don't think this was solved as I just got the same error, with `temp/read_breakpoint/read_breakpoint_per_base.txt` remaining empty. Is there a fix? 
As I need to rerun `metaMIC extract_feature` and this takes quite some time for my metagenomes, is there a way to restart it from the last step it stopped at by any chance?
There's no versioning of the software that I can see, but I cloned the github repository last week.
