### ISSUE TITLE
ModuleNotFoundError: No module named 'joblib'

### ISSUE THREAD

**Issue by lauramason326** [ZhaoXM-Lab/metaMIC#7]
Hello
I'm looking forward to cleaning up some messy assemblies! First though, I think I am having some kind of install issue. I have followed the instructions for conda install from the git hub, and it all seems to work until the last steps: 
```
(metaMIC_env) metaMIC -h
Traceback (most recent call last):
  File "/users/PAS1212/lauramason326/miniconda3/envs/metaMIC_env/bin/metaMIC", line 33, in <module>
    sys.exit(load_entry_point('metaMIC==0.0.0', 'console_scripts', 'metaMIC')())
  File "/users/PAS1212/lauramason326/miniconda3/envs/metaMIC_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 486, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/users/PAS1212/lauramason326/miniconda3/envs/metaMIC_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2867, in load_entry_point
    return ep.load()
  File "/users/PAS1212/lauramason326/miniconda3/envs/metaMIC_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2471, in load
    return self.resolve()
  File "/users/PAS1212/lauramason326/miniconda3/envs/metaMIC_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2477, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/users/PAS1212/lauramason326/miniconda3/envs/metaMIC_env/lib/python3.7/site-packages/metaMIC-0.0.0-py3.7.egg/metaMIC/metaMIC.py", line 20, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
(metaMIC_env) metaMIC download_model
Traceback (most recent call last):
  File "/users/PAS1212/lauramason326/miniconda3/envs/metaMIC_env/bin/metaMIC", line 33, in <module>
    sys.exit(load_entry_point('metaMIC==0.0.0', 'console_scripts', 'metaMIC')())
  File "/users/PAS1212/lauramason326/miniconda3/envs/metaMIC_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 486, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/users/PAS1212/lauramason326/miniconda3/envs/metaMIC_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2867, in load_entry_point
    return ep.load()
  File "/users/PAS1212/lauramason326/miniconda3/envs/metaMIC_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2471, in load
    return self.resolve()
  File "/users/PAS1212/lauramason326/miniconda3/envs/metaMIC_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2477, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/users/PAS1212/lauramason326/miniconda3/envs/metaMIC_env/lib/python3.7/site-packages/metaMIC-0.0.0-py3.7.egg/metaMIC/metaMIC.py", line 20, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
```
Any suggetsions? 
Thanks in advance
Laura

**Comment by RolandWirth** [comment]
Dear Developers,

The same problem occurs when trying to call metaMIC -h. 
"ModuleNotFoundError: No module named 'joblib'"

Best,
Roland

**Comment by cdiazmun** [comment]
Hi there! 

I encountered the same problem but it could be solved by installing the missing module with `pip install joblib`. Make sure you're using the correct `pip` (if you created a conda environment for example, call the `pip` from the metaMIC environment). Most probably it will also ask to install other missing modules. To me it asked `scikit-learn` and `requests`. 

I hope it helped!

**Comment by RolandWirth** [comment]
Hi cdiazmun!

Yes, indeed installing the required module with pip solved the problem. 

Thank you.
